resources:
  repositories:
    - repository: wwtguide
      type: github
      name: WorldWideTelescope/zola-wwtguide
      endpoint: wwtelescope

jobs:
- template: azure-build-and-publish.yml@wwtguide
