base_url = "docs.worldwidetelescope.org/user-manual"
title = "The AAS WorldWide Telescope User Manual"
description = "AAS WorldWide Telescope is a tool for showcasing astronomical data and knowledge."
theme = "wwtguide"

[extra]
github_base = "//github.com/WorldWideTelescope/worldwide-telescope-manual"
